name: Building Debug app

on:
  push:
    branches:
      - 'no-action' # non viene mai eseguita
#  pull_request:
#    branches:
#      - '**'

jobs:
  build_app:
    name: Building app
    runs-on: macos-latest
#    env:
#      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - uses: actions/cache@v3
        with:
          path: /Users/runner/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build Android Debug app
        run: ./gradlew assembleDebug

      - name: Build iOS Debug app
        run: xcodebuild -allowProvisioningUpdates -workspace iosApp/iosApp.xcodeproj/project.xcworkspace -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 15' build

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: composeApp/build/outputs/apk/debug/**.apk
          overwrite: true
          retention-days: 90